Continuous Deployment Preparation
jenkinsci/conjur-credentials-plugin pull request #27
Opened 2023-05-19 10:13 UTC by hughsaunders

This PR prepares this plugin for continuous deployment by adding a github workflow for pushing artifacts to artifactory.

This is slightly different from the usual process, as the workflow does not create github releases. That will be handled by an internal Jenkins pipeline.
Implemented Changes

The added workflow is based on https://github.com/jenkins-infra/github-reusable-workflows/blob/main/.github/workflows/maven-cd.yml

### Testing done
No testing so far, its my understanding that CD permissions are required to gain access to the required secrets. But CD access isn't granted until a PR for CD prep has been created, hence this PR.

### Submitter checklist

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2023-05-20 08:07 UTC, NotMyFault requested changes
This is not CD per JEP-229. The workflow still invokes the maven release plugin.
I recommend taking a look at the [documentation](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) outlining which files need to be adjusted and added.

2023-05-20 08:31 UTC, hughsaunders commented
@NotMyFault I realise this is non standard but we can't use the normal process as it doesn't fit with our internal release process. Please can you approve this so we can use the parts of the cd process that we need?

2023-05-20 08:35 UTC, hughsaunders commented
@NotMyFault our internal pipeline will create the GitHub release, so we only need the pipeline to upload the artifacts to artifactory. If we follow the cd process in the documentation you linked, we'll end up with two GitHub releases for each release. 

If there's another approach to this that would be more acceptable, I'm happy to make modifications.

2023-05-22 10:44 UTC, NotMyFault commented
> If there's another approach to this that would be more acceptable, I'm happy to make modifications.

I recommend sticking to the maven release plugin or following the CD standards according to the documentation. Combining both is undesired.

2023-06-14 12:01 UTC, hughsaunders commented
OK, we'll DIY with the release plugin.

2023-06-14 12:01 UTC, closed without merging