fix certificate null pointer exception when conjur plugin is used in combination of JCASC plugin
jenkinsci/conjur-credentials-plugin pull request #3
Opened 2020-12-22 08:59 UTC by mbuccarello

This fix allow conjur plugin to work correctly with the JCASC plugin avoiding a null point exeception when the conjur certificate is configured in the jenkins CACERTS instead of .p12 uploaded as a jenkins certificate.

2021-01-21 23:13 UTC, cyberark-bizdev approved these changes

2021-01-21 23:35 UTC, cyberark-bizdev commented
Michelle, 

Could you please resubmit, for some reason it is failing checks. 

Thanks

2021-01-21 23:36 UTC, cyberark-bizdev requested changes
Please resubmit... it is not passing checks.

2021-01-22 08:03 UTC, mbuccarello commented
> Please resubmit... it is not passing checks.

How I can resubmit this PR?

2021-01-22 09:01 UTC, mbuccarello commented
Hi, I did an empty PR but it still failing some test.

2021-07-12 22:56 UTC, cyberark-bizdev commented
Included in #4

2021-09-24 07:11 UTC, closed without merging

2021-09-24 07:12 UTC, cyberark-bizdev commented
Already included in main/master branch update.